version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=simpl_forum
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./app/db_table:/docker-entrypoint-initdb.d" # init db with default table / sync
  www:
    image: php:apache
    volumes:
      - "./app:/var/www/html"
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306